import '../styles/globals.css'
import Header from './components/Header'
import Image from "next/image";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <head />
      <body> 
        <Header /> 
        {children}
        </body>
    </html>
  )
}
